export enum RiskCategory {
  INVASION = "INVASION",
  ABDUCTION = "ABDUCTION",
  VIRUS_XENO = "VIRUS_XENO",
  UFO_CRASH = "UFO_CRASH",
  MIND_CONTROL = "MIND_CONTROL",
  QUANTUM_ANOMALY = "QUANTUM_ANOMALY",
}
